export const languages = {
	buttons: {
		delete: { en: 'Delete', he: 'מחק' },
		edit: { en: 'Edit', he: 'ערוך' },
		add: { en: 'Add', he: 'הוסף' },
		transfer: { en: 'Transfer', he: 'העבר' },
		itemPlus: { en: 'Item +', he: 'פריט +' },
		categoryPlus: {en: 'Category +', he: 'קטגוריה +'},
		hebrew: { en: 'עברית', he: 'עברית' },
		moveItems: { en: 'Move items', he: 'סדר פריטים' },
		moveCategories: { en: 'Move categories', he: 'סדר קטגוריות' },
		share: { en: 'Share', he: 'שיתוף' },
		copyAsText: { en: 'Copy as text', he: 'העתק כטקסט' },
		copyListToClipboard: { en: 'Copy list to clipboard', he: 'העתק רשימה ללוח הכתיבה' },
		close: { en: 'close', he: 'סגור' },
		signout: { en: 'Sign out', he: 'התנתק' },
		signin: { en: 'Sign in', he: 'התחבר' },
		signup: { en: 'Sign up', he: 'הרשם' },
		googleSignin: { en: 'Google', he: 'גוגל' },
		done: { en: 'Done', he: 'אישור' },
		// close: { en: '', he: '' },
	},
	content: {
		notLoggedIn: {en: 'You are not signed in', he: 'אתה לא מחובר'},
		newCategoryName: {en: 'Category Name (new)', he: 'שם קטגוריה (חדשה)'},
		editCategoryName: {en: 'Category Name (edit)', he: 'שם קטגוריה (עריכה)'},
		moveCategories: { en: 'Move categories', he: 'סדר קטגוריות' },
		moveItems: { en: 'Move items', he: 'סדר פריטים' },
		newItem: {en: 'New Item', he: 'פריט חדש'},
		editItem: {en: 'Edit Item', he: 'ערוך פריט'},
		transferItem: {en: '', he: ''},
		chooseCategory: {en: 'Choose category', he: 'בחר קטגוריה'},
		name: {en: 'Name', he: 'שם'},
		description: {en: 'Description', he: 'תיאור'},
		quantity: {en: 'Quantity', he: 'כמות'},
		signin: { en: 'Sign in', he: 'התחבר' },
		signup: { en: 'Sign up', he: 'הרשם' },
		password: { en: 'Password', he: 'סיסמה' },
		email: { en: 'Email', he: 'אימייל' },
		title: { en: 'Shopping List', he: 'רשימת קניות' },
		// notLoggedIn: {en: '', he: ''},
	}
};
